### ISSUE TITLE
refactor: change style of hamburger menu icons

### ISSUE THREAD

**Issue by anicmarko9** [anicmarko9/responsive-front#115]
Currently, icons inside of hamburger menu are filled with `bg-black` style (meaning background-color: black). But I want to make them consistent with icons inside my first content (`stats`). You can see there that suitcase icon, and message bubble icon are not filled with background, but rather edges. Only edges are filled with color, while their background color is transparent. I want the same thing for hamburger menu icons.

I don't think that we can change that with TailwindCSS, but if we can, then we need to change from `bg-primary` to `text-primary`. Otherwise, we need to import different icons.

**Comment by coder-abdo** [comment]
hi @anicmarko9 
after inspecting the element the problem is the `hover:bg-primary` By removing this hover effect we can just add the hover effect with text rather than background color, I remove the text-primary color from the default state and add `text-primary` on the hover state what do you think?

**Comment by anicmarko9** [comment]
Yes, I was thinking the same thing. But I'm not sure if it's really going to work. Try it, and we shall see the results.

**Comment by anicmarko9** [comment]
Nope, that's not what I wanted. Make sure you run `npm run start` and actually see for yourself how does it look like.
