### ISSUE TITLE
Enhancement: Revamping the Sidebar/Hamburger Menu Component

### ISSUE THREAD

**Issue by SameerJS6** [anicmarko9/responsive-front#86]
### Problems Identified
- Upon reviewing the code for the sidebar/hamburger menu, it is evident that there are several irrelevant/unnecessary code segments present. Removing these unnecessary code segments and incorporating more contemporary/modern techniques would undoubtedly enhance the functionality of the menu.

- Additionally, there are issues with the speed at which the menu opens and closes. The sluggish animation is further compounded by the menu occupying the entire width of the screen. This design choice appears to lack logic, as there are no corresponding links or elements that warrant such extensive screen coverage.

- Furthermore, the menu's appearance comes across as incomplete and somewhat barren.

### Proposed Solution
1. To address the above-mentioned issues, I recommend a comprehensive overhaul of the Sidebar/Hamburger Menu Component using contemporary/modern development practices. This approach would result in cleaner and more streamlined code.

1. The current iteration of the Sidebar is reliant on a `setWindowWidth` state, originating from a particular functionality. However, this dependence can be eliminated by adopting the `useClickOutside` Hook, thus simplifying and modernizing the codebase.

1. Introducing icons adjacent to the links could potentially resolve this aesthetic deficiency.

1. Moreover, it might be advantageous to consider a complete redesign of the Sidebar. The existing design, while straightforward, may benefit from a more intricate approach.

1. By reimagining the Sidebar with a focus on modernization, efficiency, and aesthetics, we can ensure a more engaging and seamless user experience. This not only addresses the issues at hand but also positions the menu for future enhancements and scalability.

### Current Menu:

 ![Current Menu 1](https://github.com/anicmarko9/responsive-front/assets/110624457/35ceb20f-6acb-49f1-99e4-fa0cdc879e5a)

### New Proposed Menu:
![New Menu 1](https://github.com/anicmarko9/responsive-front/assets/110624457/79f631b5-93ca-4681-a526-a4d3e428da14)

### Video Showcase
You can also watch a video showcasing the new proposed menu: [Video Showcase](https://github.com/anicmarko9/responsive-front/assets/110624457/81b43d7d-5093-44d1-9d4b-3433d9a07ffa)

**Comment by anicmarko9** [comment]
I like these new changes, thanks for taking your time to point out some inconsistencies. However, you don't need to spend your time on this repository, since I use it only to attract beginners; so basically, a lot of people are using this repo for practice only.

If you want to contribute to some serious repositories, since your skills are not beginner level, you can check out these two repositories:
1. [EU Tours](https://github.com/anicmarko9/eu-tours) - this is my most recent side project, but I haven't been able to do anything on it for a long time since I'm stuck with my 9 - 5 job. I'm really passionate about this repo, and it has some easy to fix issues, especially on the front end.
2. [JWT Auth](https://github.com/anicmarko9/jwt-auth) - this is one of my first projects, which means it's pretty bad. But I also care about it because it has so many different things in it. There are a lot of code refactoring needs that you don't even need to look for an issue, just freestyle.

But please, only check them out if you have your free time. Thanks for your previous contributions, cheers 🍻

**Comment by SameerJS6** [comment]
>  If you want to contribute to some serious repositories since your skills are not beginner-level.

First, Thank You, but I am only a beginner.

> You can check out these two repositories.

 Regarding your other two repositories, I will definitely take a look at them. Whenever I am free, I will surely try to contribute to them.
Thank You
